### PR TITLE
register on literal block in addition to listing block

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by eshepelyuk** [comment]
May you explain the purpose os this change ? Not really understanding what it could bring

**Comment by mojavelinux** [comment]
I did add a test that it is registered on the literal block. I don't think we have to test every permutation as Asciidoctor gives us the guarantee that the two blocks will operate the same.

I am missing a test for the use of cloaked-context though.

**Comment by eshepelyuk** [comment]
> I am missing a test for the use of cloaked-context though.
Should we merge only after this test ? What is the scenario of testing this ?

**Comment by mojavelinux** [comment]
Yep, I'll send the test. Just forgot.

**Comment by mojavelinux** [comment]
Test added. We just want to make sure we preserve the original block on an error.

**Pull request merged**
