### PR TITLE
Add a check whether an image already exists in the content catalog (#59)

### PR DESCRIPTION
**Pull request by andreas-schilling**

### CODE REVIEW

**Comment by eshepelyuk** [comment]
Would it be possible to write a test for this ?

**Comment by andreas-schilling** [comment]
Hmm, possibly by someone who actually knows JS ;-)
Currently I have problems running the tests at all, also without my changes many of them fail on my machine. Not sure whether this is caused by the fact that I'm on windows?

**Comment by eshepelyuk** [comment]
I did all this development on windows :)

**Comment by andreas-schilling** [comment]
Added a test. Another one is still failing with non matching hashes, however I wonder whether this might be due to changes on PlantUML side? I don't know how the reference hashes were initially determined?

**Comment by andreas-schilling** [comment]
Ping :)

**Comment by eshepelyuk** [comment]
Sorry, was on vacations.

**Comment by eshepelyuk** [comment]
Release process had to be changed , I need to spend my time on this.
So, can you wait some more time ?

**Comment by andreas-schilling** [comment]
Sure, np :)

**Comment by eshepelyuk** [comment]
@andreas-schilling https://www.npmjs.com/package/asciidoctor-plantuml/v/1.2.0

**Pull request merged**
