### PR TITLE
resolves #76 support svg inline

### LINKED ISSUE #76: The extension should support inline and interactive for svgs
asciidoctor provides support for inline and interactive for svg images.  The extension can pass through the plantuml url with appropriate block attributes to hook into this.

### PR DESCRIPTION
**Pull request by djencks**

### CODE REVIEW

**Comment by djencks** [comment]
I agree that the positional attributes don't belong in the same table as the page/global attributes. I'm proposing introducing another positional attribute not supported AFAICT by `asciidoctor-diagram`.  What would you think of another table showing all the positional attributes?  I'd find the README more useful if it had a complete configuration guide for this specific extension than if I have to refer to some other more general documentation.

**Comment by djencks** [comment]
I worked some more on the README, what do you think?  I'd like to try out some more combinations in antora before this gets merged, I haven't tried the inline macro yet.

**Comment by djencks** [comment]
1,2 done, good idea...
Re 3, are you really wanting the meaning of the README to be like this?

```
 |===
 
-.Named or positional block or macro attributes
-[cols="3,1,8"]
-|===
-|Attribute |Position |Description
-
-|target 
-|0
-|The name of the file generated, if the diagram is downloaded.
-
-|format 
-|1
-|The format (`svg` or `png`) of the diagram.
-
-|options or opts 
-|2
-|Unspecified for link to diagram, `inline` for inline svg, or `interactive` for interactive object.
-
-|===
-
-For instance,
-
-```
-[plantuml, target=myImage, format=svg, opts=inline]
-...
-```
-is equivalent to
-```
-[plantuml, myImage, svg, inline]
-...
-```
-
-[NOTE]
-The `inline` option relies on asciidoctor inline remote svg support.
-Consult the asciidoctor documentation for additional configuration requirements for `allow-uri-read` and `safe`.
+Positional attributes for AsciiDoctor Diagram are documented https://asciidoctor.org/docs/asciidoctor-diagram/#creating-a-diagram[here].
+Although there are some similarities to the asciidoctor-plantuml positional attribute usage, there are more differences.
+In addition, there is a secret undocumented asciidoctor-plantuml positional attribute that you can study the code to find.
 ```

**Comment by djencks** [comment]
oops I left in some logging!!

**Comment by djencks** [comment]
There seems to be something wrong now with downloading png images.  It may be a few days before I can investigate.

**Comment by djencks** [comment]
I fixed the png download problem. More antora tests would have revealed it...

**Comment by eshepelyuk** [comment]
1. As far as I understood - you've introduced a new positional parameter (`inline`). we should not do this, since it's breaking the compatibility with `Asciidoctor Diagram`. Plz make this as only named atrribute to a diagram ( named attributes are not breaking compatibilities)
1. README
    * since positional attributes are just copy of ones from `Asciidoctor Diagram` - there's no need to document them in this plugin, please remove corresponding section about positional attributes
     * since you've introduced new named attribute - please add a new section only for `addtional named attributes` (i.e. a single one you've introduced)

**Comment by djencks** [comment]
Your requests are reasonable, and let me see if I can convince you that what I've written is more reasonable :-).  At this point I'm not sure if having options/opts as a positional rather than named attribute is actually useful; that's the least important part for me. 

I think that completely documenting the behavior of this plugin in one place will be much more useful than pointing to some other documentation that is only partly applicable although similar. Here are some differences between this plugin and asciidoctor-diagram:

- This plugin can generate from multiple source diagram formats from the same `plantuml` name; in the other plugin the documentation implies that each source diagram format uses its own name.
- By default, with this plugin, the first positional attribute `target` is ignored; you have to set the page/global `plantuml-fetch-diagram` attribute for the `target` to be relevant.
- The supported output formats are only `svg` and `png`, not `txt`.

As a beginning user of this plugin, and being rather mystified by ruby, I would certainly have found it much easier to understand how to use this plugin if its documentation was self contained rather than referring to documentation for something in a different language, with different usage, and only somewhat related configuration. I was quite confused when I first read the documentation, and more confused when I tried to figure out how this plugin configuration related to the asciidoctor-diagram configuration.

**Comment by eshepelyuk** [comment]
@djencks look, let me describe a scenario :)

we have an ADOC file in git with PlantUML diagram within.
And, this file **must be**  valid both for `Antora` and pure cmd line `Asciidoctor`.

Yeah, I see the movement that once upon a time the `Ruby` version will be abandoned or deprecated. 
But, for now, there are two great producst: Antora (NodeJS) and Asciidoctor(Ruby) and **the single markup** to rule them all.

So, the intention of this (JS \ Antora oriented) extension - is to be 100% compatible with `Ruby` based `Asciidoctor`.

**Comment by djencks** [comment]
Since you are concerned with compatibility with asciidoctor-diagram, I wrote up a detailed guide to compatibility.  I'm not at all sure I've put it in the most appropriate place in the README.

My point of view is that although the configuration of this extension and the asciidoctor-diagram are fairly compatible in their area of overlap, that overlap is actually rather small and that relying on the asciidoctor-diagram documentation for configuring this extension will be excessively confusing for someone who wants the full capabilities of this extension without regard for those of asciidoctor-diagram.

While I still think having options/opts as a positional attribute is a good idea, I'm willing to make it named-only because I think the most useful situation is svg + inline, in which case, using positional attributes, one must specify a target value which will be unused or ignored.

**Comment by djencks** [comment]
I noticed that in plain asciidoctor images the opts/options attribute is not positional, so I now agree it shouldn't be positional here either.  I've updated the code, tests, and documentation to reflect this.  I hope we can agree soon on the most appropriate documentation!

By the way, can you run the tests against a local plantuml server?  When I run the tests locally I usually get many "too many requests" responses from the remote server, which makes it very difficult to find problems, but running against a local plantuml server there are a lot of hash differences.  Am I doing something wrong, or do you know how to fix the hash problem?

**Comment by eshepelyuk** [comment]
> By the way, can you run the tests against a local plantuml server? When I run the tests locally I usually get many "too many requests" responses from the remote server, which makes it very difficult to find problems, but running against a local plantuml server there are a lot of hash differences. Am I doing something wrong, or do you know how to fix the hash problem?

yes, a while ago whwn developed locally - i ran test succesfully. moreover i didn't ever see issues on Travis CI .
but, this could be a great addition to modify test scripts to run agains local PlantUML server, I'd go with smth like https://github.com/testcontainers/testcontainers-node

**Comment by eshepelyuk** [comment]
As usual :( 
plz rebase

**Comment by djencks** [comment]
What can I do to move this forward?  I've indicated what I think the documentation would best contain, and am happy to make it conform to whatever you would like.

**Comment by eshepelyuk** [comment]
Sorry @djencks 
Got unexpectedly busy with work stuff. I'll manage the code and release new version as soon as have some free time, without changing docs, that we can keep discussing and improving further.

**Comment by djencks** [comment]
Thanks!

**Pull request closed without merging**
