### PR TITLE
Resolves #38, apply substitutions

### LINKED ISSUE #34: fake issue to test release process

### LINKED ISSUE #38: Implement substitutions support inside plantuml block
The attributes substitution doesn't work .

here is an example : 

```
:bloc-annotation: testing annotation

[subs="attributes"]
[plantuml]
....
@startuml
 
rectangle "Bloc 1" <<$archimate/network>> as blk1 #lightblue 

rectangle "bloc 2" <<$archimate/network>> as blk2 #lightgray 

blk1 ==> blk2 : {bloc-annotation}

@enduml
....
```
in the resulting diagram {bloc-annotation} has not been replaced.

May be a missing preprocessor call ?

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@Mogztter unfortunately broken :(

**Comment by Mogztter** [comment]
Ooops I read 34 but you're right the issue number is 38 :sweat_smile:

**Comment by Mogztter** [comment]
> unfortunately broken :(

Pull request #39 should go first. I believe the build will be green once rebased.

**Comment by eshepelyuk** [comment]
@Mogztter merged PR #39 - let's try rebase this one :)

**Pull request merged**
