### PR TITLE
resolves #10 return pure AST nodes instead of HTML passthrough nodes

### LINKED ISSUE #10: Extension should not emit raw HTML
An Asciidoctor syntax extension should not emit raw HTML. Instead, it should return an AST node, which will get converted to HTML automatically by the converter. This does mean giving up some control over the HTML that is created, but it also means that the extension can be used to produce other formats, such as DocBook.

(If you want to customize the HTML, then that should be handled using a separate, supplemental extension to the HTML converter).

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
This PR is going to conflict with #8. However, I think this should be resolved before that one so that both use the same AST modification strategy.

**Comment by eshepelyuk** [comment]
Could you add test cases for `alt` and `roles` attributes, added by this PR ?

**Comment by mojavelinux** [comment]
I sure can!

**Comment by mojavelinux** [comment]
Btw, we'll be able to simplify this further by using the createImageBlock method once Asciidoctor 1.5.6 is out.

**Comment by eshepelyuk** [comment]
@mojavelinux could you also remove `id` positional argument and introduce proper support for id ?

**Comment by mojavelinux** [comment]
PR rebased and updated to include additional tests!

**Pull request merged**
